name: "Publish marketplace XML"

on:
  release:
    types: [released]

jobs:
  call:
    permissions:
      contents: "write"
    uses: "ticgal/.github/.github/workflows/publish-marketplace-xml.yml@master"
